<?php

$mimetypes = [

// ======================================================================
// IMAGE FORMATS
// ======================================================================

    '3ds'           => 'image/x-3ds'
,   'bmp'           => 'image/bmp'
,   'btif'          => 'image/prs.btif'
,   'cgm'           => 'image/cgm'
,   'cmx'           => 'image/x-cmx'
,   'djv'           => 'image/vnd.djvu'
,   'djvu'          => 'image/vnd.djvu'
,   'dwg'           => 'image/vnd.dwg'
,   'dxf'           => 'image/vnd.dxf'
,   'fbs'           => 'image/vnd.fastbidsheet'
,   'fh'            => 'image/x-freehand'
,   'fh4'           => 'image/x-freehand'
,   'fh5'           => 'image/x-freehand'
,   'fh7'           => 'image/x-freehand'
,   'fhc'           => 'image/x-freehand'
,   'fpx'           => 'image/vnd.fpx'
,   'fst'           => 'image/vnd.fst'
,   'g3'            => 'image/g3fax'
,   'gif'           => 'image/gif'
,   'ico'           => 'image/x-icon'
,   'ief'           => 'image/ief'
,   'jpe'           => 'image/jpeg'
,   'jpeg'          => 'image/jpeg'
,   'jpg'           => 'image/jpeg'
,   'ktx'           => 'image/ktx'
,   'mdi'           => 'image/vnd.ms-modi'
,   'mmr'           => 'image/vnd.fujixerox.edmics-mmr'
,   'npx'           => 'image/vnd.net-fpx'
,   'pbm'           => 'image/x-portable-bitmap'
,   'pct'           => 'image/x-pict'
,   'pcx'           => 'image/x-pcx'
,   'pgm'           => 'image/x-portable-graymap'
,   'pic'           => 'image/x-pict'
,   'png'           => 'image/png'
,   'pnm'           => 'image/x-portable-anymap'
,   'ppm'           => 'image/x-portable-pixmap'
,   'psd'           => 'image/vnd.adobe.photoshop'
,   'ras'           => 'image/x-cmu-raster'
,   'rgb'           => 'image/x-rgb'
,   'rlc'           => 'image/vnd.fujixerox.edmics-rlc'
,   'sgi'           => 'image/sgi'
,   'sid'           => 'image/x-mrsid-image'
,   'sub'           => 'image/vnd.dvb.subtitle'
,   'svg'           => 'image/svg+xml'
,   'svgz'          => 'image/svg+xml'
,   'tga'           => 'image/x-tga'
,   'tif'           => 'image/tiff'
,   'tiff'          => 'image/tiff'
,   'uvg'           => 'image/vnd.dece.graphic'
,   'uvi'           => 'image/vnd.dece.graphic'
,   'uvvg'          => 'image/vnd.dece.graphic'
,   'uvvi'          => 'image/vnd.dece.graphic'
,   'wbmp'          => 'image/vnd.wap.wbmp'
,   'wdp'           => 'image/vnd.ms-photo'
,   'webp'          => 'image/webp'
,   'xbm'           => 'image/x-xbitmap'
,   'xif'           => 'image/vnd.xiff'
,   'xpm'           => 'image/x-xpixmap'
,   'xwd'           => 'image/x-xwindowdump'



// ======================================================================
// TEXT FORMATS
// ======================================================================

,   'appcache'      => 'text/cache-manifest'
,   'asm'           => 'text/x-asm'
,   'c'             => 'text/x-c'
,   'cc'            => 'text/x-c'
,   'conf'          => 'text/plain'
,   'cpp'           => 'text/x-c'
,   'css'           => 'text/css'
,   'csv'           => 'text/csv'
,   'cxx'           => 'text/x-c'
,   'def'           => 'text/plain'
,   'dic'           => 'text/x-c'
,   'dsc'           => 'text/prs.lines.tag'
,   'etx'           => 'text/x-setext'
,   'f'             => 'text/x-fortran'
,   'f77'           => 'text/x-fortran'
,   'f90'           => 'text/x-fortran'
,   'for'           => 'text/x-fortran'
,   'h'             => 'text/x-c'
,   'hh'            => 'text/x-c'
,   'htm'           => 'text/html'
,   'html'          => 'text/html'
,   'swig'          => 'text/html'
,   'twig'          => 'text/html'
,   'njk'           => 'text/html'
,   'ejs'           => 'text/html'
,   'ics'           => 'text/calendar'
,   'ifb'           => 'text/calendar'
,   'in'            => 'text/plain'
,   'java'          => 'text/x-java-source'
,   'list'          => 'text/plain'
,   'log'           => 'text/plain'
,   'man'           => 'text/troff'
,   'me'            => 'text/troff'
,   'ms'            => 'text/troff'
,   'n3'            => 'text/n3'
,   'nfo'           => 'text/x-nfo'
,   'opml'          => 'text/x-opml'
,   'p'             => 'text/x-pascal'
,   'pas'           => 'text/x-pascal'
,   'roff'          => 'text/troff'
,   'rtx'           => 'text/richtext'
,   's'             => 'text/x-asm'
,   'sfv'           => 'text/x-sfv'
,   'sgm'           => 'text/sgml'
,   'sgml'          => 'text/sgml'
,   't'             => 'text/troff'
,   'text'          => 'text/plain'
,   'tr'            => 'text/troff'
,   'tsv'           => 'text/tab-separated-values'
,   'ttl'           => 'text/turtle'
,   'txt'           => 'text/plain'
,   'uri'           => 'text/uri-list'
,   'uris'          => 'text/uri-list'
,   'urls'          => 'text/uri-list'
,   'uu'            => 'text/x-uuencode'
,   'vcard'         => 'text/vcard'
,   'vcf'           => 'text/x-vcard'
,   'vcs'           => 'text/x-vcalendar'



// ======================================================================
// VIDEO FORMATS
// ======================================================================

,   '3g2'           => 'video/3gpp2'
,   '3gp'           => 'video/3gpp'
,   'asf'           => 'video/x-ms-asf'
,   'asx'           => 'video/x-ms-asf'
,   'avi'           => 'video/x-msvideo'
,   'f4v'           => 'video/x-f4v'
,   'fli'           => 'video/x-fli'
,   'flv'           => 'video/x-flv'
,   'h261'          => 'video/h261'
,   'h263'          => 'video/h263'
,   'h264'          => 'video/h264'
,   'jpgm'          => 'video/jpm'
,   'jpgv'          => 'video/jpeg'
,   'jpm'           => 'video/jpm'
,   'm1v'           => 'video/mpeg'
,   'm2v'           => 'video/mpeg'
,   'm4v'           => 'video/x-m4v'
,   'mj2'           => 'video/mj2'
,   'mjp2'          => 'video/mj2'
,   'mk3d'          => 'video/x-matroska'
,   'mks'           => 'video/x-matroska'
,   'mkv'           => 'video/x-matroska'
,   'mng'           => 'video/x-mng'
,   'mov'           => 'video/quicktime'
,   'movie'         => 'video/x-sgi-movie'
,   'mp4'           => 'video/mp4'
,   'mp4v'          => 'video/mp4'
,   'mpe'           => 'video/mpeg'
,   'mpeg'          => 'video/mpeg'
,   'mpg'           => 'video/mpeg'
,   'mpg4'          => 'video/mp4'
,   'ogv'           => 'video/ogg'
,   'qt'            => 'video/quicktime'
,   'smv'           => 'video/x-smv'
,   'vob'           => 'video/x-ms-vob'
,   'webm'          => 'video/webm'
,   'wm'            => 'video/x-ms-wm'
,   'wmv'           => 'video/x-ms-wmv'
,   'wmx'           => 'video/x-ms-wmx'
,   'wvx'           => 'video/x-ms-wvx'



// ======================================================================
// AUDIO FORMATS
// ======================================================================

,   'aac'           => 'audio/x-aac'
,   'adp'           => 'audio/adpcm'
,   'aif'           => 'audio/x-aiff'
,   'aifc'          => 'audio/x-aiff'
,   'aiff'          => 'audio/x-aiff'
,   'au'            => 'audio/basic'
,   'caf'           => 'audio/x-caf'
,   'flac'          => 'audio/x-flac'
,   'kar'           => 'audio/midi'
,   'm2a'           => 'audio/mpeg'
,   'm3a'           => 'audio/mpeg'
,   'm3u'           => 'audio/x-mpegurl'
,   'm4a'           => 'audio/mp4'
,   'mid'           => 'audio/midi'
,   'midi'          => 'audio/midi'
,   'mka'           => 'audio/x-matroska'
,   'mp2'           => 'audio/mpeg'
,   'mp2a'          => 'audio/mpeg'
,   'mp3'           => 'audio/mpeg'
,   'mp4a'          => 'audio/mp4'
,   'mpga'          => 'audio/mpeg'
,   'oga'           => 'audio/ogg'
,   'ogg'           => 'audio/ogg'
,   'ra'            => 'audio/x-pn-realaudio'
,   'ram'           => 'audio/x-pn-realaudio'
,   'rmi'           => 'audio/midi'
,   'rmp'           => 'audio/x-pn-realaudio-plugin'
,   's3m'           => 'audio/s3m'
,   'sil'           => 'audio/silk'
,   'snd'           => 'audio/basic'
,   'spx'           => 'audio/ogg'
,   'wav'           => 'audio/x-wav'
,   'wax'           => 'audio/x-ms-wax'
,   'weba'          => 'audio/webm'
,   'wma'           => 'audio/x-ms-wma'
,   'xm'            => 'audio/xm'



// ======================================================================
// CHEMICAL FORMATS
// ======================================================================




// ======================================================================
// MODEL FORMATS
// ======================================================================

,   'iges'          => 'model/iges'
,   'igs'           => 'model/iges'
,   'mesh'          => 'model/mesh'
,   'msh'           => 'model/mesh'
,   'silo'          => 'model/mesh'
,   'vrml'          => 'model/vrml'
,   'wrl'           => 'model/vrml'



// ======================================================================
// MESSAGE FORMATS
// ======================================================================
,   'eml'           => 'message/rfc822'
,   'mime'          => 'message/rfc822'



// ======================================================================
// X-CONFERENCE FORMATS
// ======================================================================

,   'ice'           => 'x-conference/x-cooltalk'



// ======================================================================
// APPLICATION FORMATS
// ======================================================================

,   '7z'            => 'application/x-7z-compressed'
,   'ac'            => 'application/pkix-attr-cert'
,   'ai'            => 'application/postscript'
,   'asc'           => 'application/pgp-signature'
,   'atom'          => 'application/atom+xml'
,   'atomcat'       => 'application/atomcat+xml'
,   'atomsvc'       => 'application/atomsvc+xml'
,   'aw'            => 'application/applixware'
,   'bin'           => 'application/octet-stream'
,   'bpk'           => 'application/octet-stream'
,   'bz'            => 'application/x-bzip'
,   'bz2'           => 'application/x-bzip2'
,   'cbr'           => 'application/x-cbr'
,   'ccxml'         => 'application/ccxml+xml'
,   'cdmia'         => 'application/cdmi-capability'
,   'cdmic'         => 'application/cdmi-container'
,   'cdmid'         => 'application/cdmi-domain'
,   'cdmio'         => 'application/cdmi-object'
,   'cdmiq'         => 'application/cdmi-queue'
,   'cer'           => 'application/pkix-cert'
,   'class'         => 'application/java-vm'
,   'cpt'           => 'application/mac-compactpro'
,   'crl'           => 'application/pkix-crl'
,   'cu'            => 'application/cu-seeme'
,   'cww'           => 'application/prs.cww'
,   'davmount'      => 'application/davmount+xml'
,   'dbk'           => 'application/docbook+xml'
,   'deploy'        => 'application/octet-stream'
,   'dist'          => 'application/octet-stream'
,   'distz'         => 'application/octet-stream'
,   'dms'           => 'application/octet-stream'
,   'doc'           => 'application/msword'
,   'dot'           => 'application/msword'
,   'dssc'          => 'application/dssc+der'
,   'dtd'           => 'application/xml-dtd'
,   'dump'          => 'application/octet-stream'
,   'ecma'          => 'application/ecmascript'
,   'elc'           => 'application/octet-stream'
,   'emma'          => 'application/emma+xml'
,   'eps'           => 'application/postscript'
,   'epub'          => 'application/epub+zip'
,   'exi'           => 'application/exi'
,   'ez'            => 'application/andrew-inset'
,   'gbr'           => 'application/rpki-ghostbusters'
,   'gml'           => 'application/gml+xml'
,   'gpx'           => 'application/gpx+xml'
,   'gram'          => 'application/srgs'
,   'grxml'         => 'application/srgs+xml'
,   'gxf'           => 'application/gxf'
,   'hlp'           => 'application/winhlp'
,   'hqx'           => 'application/mac-binhex40'
,   'ink'           => 'application/inkml+xml'
,   'inkml'         => 'application/inkml+xml'
,   'ipfix'         => 'application/ipfix'
,   'jar'           => 'application/java-archive'
,   'js'            => 'application/javascript'
,   'json'          => 'application/json'
,   'jsonml'        => 'application/jsonml+json'
,   'lostxml'       => 'application/lost+xml'
,   'lrf'           => 'application/octet-stream'
,   'm21'           => 'application/mp21'
,   'ma'            => 'application/mathematica'
,   'mads'          => 'application/mads+xml'
,   'mar'           => 'application/octet-stream'
,   'mathml'        => 'application/mathml+xml'
,   'mb'            => 'application/mathematica'
,   'mbox'          => 'application/mbox'
,   'meta4'         => 'application/metalink4+xml'
,   'metalink'      => 'application/metalink+xml'
,   'mets'          => 'application/mets+xml'
,   'mft'           => 'application/rpki-manifest'
,   'mods'          => 'application/mods+xml'
,   'mp21'          => 'application/mp21'
,   'mp4s'          => 'application/mp4'
,   'mrc'           => 'application/marc'
,   'mrcx'          => 'application/marcxml+xml'
,   'mscml'         => 'application/mediaservercontrol+xml'
,   'mxf'           => 'application/mxf'
,   'mxml'          => 'application/xv+xml'
,   'nb'            => 'application/mathematica'
,   'oda'           => 'application/oda'
,   'ogx'           => 'application/ogg'
,   'omdoc'         => 'application/omdoc+xml'
,   'onepkg'        => 'application/onenote'
,   'onetmp'        => 'application/onenote'
,   'onetoc'        => 'application/onenote'
,   'onetoc2'       => 'application/onenote'
,   'opf'           => 'application/oebps-package+xml'
,   'oxps'          => 'application/oxps'
,   'p10'           => 'application/pkcs10'
,   'p7c'           => 'application/pkcs7-mime'
,   'p7m'           => 'application/pkcs7-mime'
,   'p7s'           => 'application/pkcs7-signature'
,   'p8'            => 'application/pkcs8'
,   'pdf'           => 'application/pdf'
,   'pfr'           => 'application/font-tdpfr'
,   'pgp'           => 'application/pgp-encrypted'
,   'pkg'           => 'application/octet-stream'
,   'pki'           => 'application/pkixcmp'
,   'pkipath'       => 'application/pkix-pkipath'
,   'pls'           => 'application/pls+xml'
,   'prf'           => 'application/pics-rules'
,   'ps'            => 'application/postscript'
,   'pskcxml'       => 'application/pskc+xml'
,   'rdf'           => 'application/rdf+xml'
,   'rif'           => 'application/reginfo+xml'
,   'rl'            => 'application/resource-lists+xml'
,   'rld'           => 'application/resource-lists-diff+xml'
,   'rnc'           => 'application/relax-ng-compact-syntax'
,   'roa'           => 'application/rpki-roa'
,   'rq'            => 'application/sparql-query'
,   'rs'            => 'application/rls-services+xml'
,   'rsd'           => 'application/rsd+xml'
,   'rss'           => 'application/rss+xml'
,   'rtf'           => 'application/rtf'
,   'sbml'          => 'application/sbml+xml'
,   'scq'           => 'application/scvp-cv-request'
,   'scs'           => 'application/scvp-cv-response'
,   'sdp'           => 'application/sdp'
,   'ser'           => 'application/java-serialized-object'
,   'setpay'        => 'application/set-payment-initiation'
,   'setreg'        => 'application/set-registration-initiation'
,   'shf'           => 'application/shf+xml'
,   'sig'           => 'application/pgp-signature'
,   'smi'           => 'application/smil+xml'
,   'smil'          => 'application/smil+xml'
,   'so'            => 'application/octet-stream'
,   'spp'           => 'application/scvp-vp-response'
,   'spq'           => 'application/scvp-vp-request'
,   'sru'           => 'application/sru+xml'
,   'srx'           => 'application/sparql-results+xml'
,   'ssdl'          => 'application/ssdl+xml'
,   'ssml'          => 'application/ssml+xml'
,   'stk'           => 'application/hyperstudio'
,   'swf'           => 'application/x-shockwave-flash'
,   'tar'           => 'application/x-tar'
,   'tei'           => 'application/tei+xml'
,   'tfi'           => 'application/thraud+xml'
,   'tsd'           => 'application/timestamped-data'
,   'ttf'           => 'application/x-font-ttf'
,   'vxml'          => 'application/voicexml+xml'
,   'wgt'           => 'application/widget'
,   'woff'          => 'application/font-woff'
,   'wsdl'          => 'application/wsdl+xml'
,   'wspolicy'      => 'application/wspolicy+xml'
,   'xaml'          => 'application/xaml+xml'
,   'xdf'           => 'application/xcap-diff+xml'
,   'xdssc'         => 'application/dssc+xml'
,   'xenc'          => 'application/xenc+xml'
,   'xer'           => 'application/patch-ops-error+xml'
,   'xht'           => 'application/xhtml+xml'
,   'xhtml'         => 'application/xhtml+xml'
,   'xhvml'         => 'application/xv+xml'
,   'xlf'           => 'application/x-xliff+xml'
,   'xml'           => 'application/xml'
,   'xop'           => 'application/xop+xml'
,   'xpi'           => 'application/x-xpinstall'
,   'xpl'           => 'application/xproc+xml'
,   'xsl'           => 'application/xml'
,   'xslt'          => 'application/xslt+xml'
,   'xspf'          => 'application/xspf+xml'
,   'xvm'           => 'application/xv+xml'
,   'xvml'          => 'application/xv+xml'
,   'xz'            => 'application/x-xz'
,   'yang'          => 'application/yang'
,   'yin'           => 'application/yin+xml'
,   'zip'           => 'application/zip'

];


!defined('MIME_TYPES') ? define('MIME_TYPES', $mimetypes) : null;
